#!/usr/bin/env bash
# Displays information about subdomains of a given domain

display_info() {
    local subdomain=$1
    local domain=$2
    local result
    result=$(dig "${subdomain}.${domain}" | awk '/ANSWER SECTION:/{getline; print}')
    local record_type
    record_type=$(echo "$result" | awk '{print $4}')
    local destination
    destination=$(echo "$result" | awk '{print $5}')
    echo "The subdomain ${subdomain} is a ${record_type} record and points to ${destination}"
}

domain=$1
subdomain=$2

if [ -z "$subdomain" ]; then
    display_info www "$domain"
    display_info lb-01 "$domain"
    display_info web-01 "$domain"
    display_info web-02 "$domain"
else
    display_info "$subdomain" "$domain"
fi

